apiVersion: v1
kind: Service
metadata:
  name: appforge
  namespace: appforge
  labels:
    app: appforge
spec:
  type: ClusterIP
  selector:
    app: appforge
  ports:
    - name: http
      port: 80
      targetPort: 3000
      protocol: TCP